{% set version = "2022.11.29" %}

package:
  name: pangeo-notebook
  version: {{ version }}

build:
  number: 0
  noarch: generic

requirements:
  run:
    - pangeo-dask =2022.11.23
    - dask-labextension =6.0.0
    - ipywidgets =8.0.2
    - jupyter-server-proxy =3.2.2
    - jupyterhub-singleuser =3.0.0
    - jupyterlab =3.5.0
    - nbgitpuller =1.1.1

test:
  commands:
    - jupyter -h

about:
  home: http://pangeo.io
  license: MIT
  license_file: LICENSE
  summary: "pangeo notebook dependencies"

extra:
  recipe-maintainers:
    - scottyhq 
    - jhamman
    - TomAugspurger
