{% set version = "2022.05.27" %}

package:
  name: pangeo-notebook
  version: {{ version }}

build:
  number: 0
  noarch: generic

requirements:
  run:
    - pangeo-dask =2022.05.27
    - dask-labextension =5.2.0
    - ipywidgets =7.7.0
    - jupyter-server-proxy =3.2.1
    - jupyterhub-singleuser =2.3.0
    - jupyterlab =3.4.2
    - nbgitpuller =1.1.0

test:
  commands:
    - jupyter -h

about:
  home: http://pangeo.io
  license: MIT
  license_file: LICENSE
  summary: "pangeo notebook dependencies"

extra:
  recipe-maintainers:
    - scottyhq 
    - jhamman
    - TomAugspurger
