{% set version = "2020.05.01" %}

package:
  name: pangeo-notebook
  version: {{ version }}

build:
  number: 1
  noarch: generic

requirements:
  run:
    - pangeo-dask =2020.05.01
    - dask-labextension =2.0.2
    - ipywidgets =7.5.1
    - jupyter-server-proxy =1.3.2
    - jupyterhub =1.1.0
    - jupyterlab <2
    - nbgitpuller =0.8.0

test:
  commands:
    - jupyter -h

about:
  home: http://pangeo.io
  license: MIT
  license_file: LICENSE
  summary: "pangeo notebook dependencies"

extra:
  recipe-maintainers:
    - scottyhq 
    - jhamman
    - TomAugspurger
