{% set version = "2020.11.06" %}

package:
  name: pangeo-notebook
  version: {{ version }}

build:
  number: 0
  noarch: generic

requirements:
  run:
    - pangeo-dask =2020.11.05
    - dask-labextension =3.0.0
    - ipywidgets =7.5.1
    - jupyter-server-proxy =1.5.0
    - jupyterhub-singleuser =1.2.1
    - jupyterlab >=2
    - nbgitpuller =0.9.0
    - nodejs >=12

test:
  commands:
    - jupyter -h

about:
  home: http://pangeo.io
  license: MIT
  license_file: LICENSE
  summary: "pangeo notebook dependencies"

extra:
  recipe-maintainers:
    - scottyhq 
    - jhamman
    - TomAugspurger
