on:
  push:
    branches:
      - master
    paths:
      - 'recipe/meta.yml'

jobs:
  webservices:
    runs-on: ubuntu-latest
    name: webservices
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT }}
          repository: pangeo-data/pangeo-docker-images
          event-type: new-notebook-metapackage
