on:
  schedule:
  #- cron:  "*/5 * * * *"
  - cron:  "0 0 * * *"
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    if: github.repository == 'pangeo-bot/pangeo-notebook-feedstock'
    steps:
    - uses: actions/checkout@master
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "conda-forge/pangeo-notebook-feedstock"
        source_branch: "master"
        destination_branch: "master"
        github_token: ${{ secrets.GITHUB_TOKEN }}
